include theos/makefiles/common.mk

APPLICATION_NAME = dropbearalertapp
dropbearalertapp_FILES = /mnt/d/codes/dropbearalert/dropbearalertapp/dropbearalertapp.mm
dropbearalertapp_FRAMEWORKS =  UIKit MessageUI Social Twitter QuartzCore CoreGraphics Foundation CoreFoundation 
dropbearalertapp_PRIVATE_FRAMEWORKS = Preferences
dropbearalertapp_LDFLAGS = -Wl,-segalign,4000
dropbearalertapp_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/application.mk

all::
